import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import AppSideBar from "./__components/Layout/AppSideBar";
import Header from "./__components/Layout/Header";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSideBar />
      <SidebarInset>
        <Header />
        <Toaster />
        <div className="p-6 bg-primary-foreground rounded-md min-h-full mx-12">
          {children}
        </div>
      </SidebarInset>
    </SidebarProvider>
  );
}
