import { SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import AppSideBar from "./__components/Layout/AppSideBar";
import Header from "./__components/Layout/Header";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSideBar />
      <div className="w-full">
        <Header />
        <div className="px-12">{children}</div>
      </div>
    </SidebarProvider>
  );
}
